### PR TITLE
Block Service: Epic Games

### PR DESCRIPTION
**Pull request by onedr0p**
Closes: https://github.com/AdguardTeam/AdGuardHome/issues/1010

Blocking `||epicgames.com^` covers pretty much all Epic Games since a lot of their games home pages e.g. fortnite.com, battlebreakers.com redirect to a sub domain off of epicgames.com.

We could include more DNS names as described in https://github.com/AdguardTeam/AdGuardHome/issues/1010 but I am unsure of any unintended side effects, or if they are really needed. Since I don't want to download and install the Epic Game store or Fortnite, we can rely on feedback from the community to block more Epic Games stuff.

### CODE REVIEW

**Comment by IldarKamalov** [comment]
Great, thanks.
Merged https://github.com/AdguardTeam/AdGuardHome/commit/8b7d23e7d0dd94ff6d4831f48951bca2e3618827

**Comment by ArchiveBase** [comment]
@IldarKamalov @onedr0p
> Blocking ||epicgames.com^ covers pretty much all Epic Games since a lot of their games home pages e.g. fortnite.com, battlebreakers.com redirect to a sub domain off of epicgames.com.

Well. maybe you must consider add (i.) and (ii.)
I. epicgames-download1.akamaized.net - source for download epicgames applications
II. ||unrealengine.com^ ||easy.ac^ - unique hosted websites, cdn and for clients

III. ||easyanticheat.net^ - (download-alt.easyanticheat.net / eac-cdn.com - download.eac-cdn.com in use for clients) https://www.easy.ac/en-us/support/game/issues/guide/

**Comment by onedr0p** [comment]
@ArchiveBase can you confirm that the clients work with just blocking `||epicgames.com^`? If the clients are able to connect and download the games we can consider blocking the other DNS names.

**Comment by ArchiveBase** [comment]
@onedr0p Got it. Thanks😊 Likely some users will need new feature😉

**Comment by ArchiveBase** [comment]
@onedr0p https://github.com/AdguardTeam/AdGuardHome/issues/1128 https://github.com/AdguardTeam/AdGuardHome/issues/1139 interested?

**Pull request closed without merging**
