### PR TITLE
Initial config for snap build

### PR DESCRIPTION
**Pull request by ted-gould**
This adds the build configuration to make a snap package for AdGuard Home. Provides an easy way to provide AdGuard Home along with auto-updating features.

Currently, I reserved the adguard-home name in the app store, but kept it private for testing. I'd much rather hand it over to the development team though.

### CODE REVIEW

**Comment by ameshkov** [comment]
Cool, thank you! 

We may need to wait a little bit on this one, I am thinking about creating a separate repo for AGH packages. People were requesting brew and deb packages as well.

**Comment by ted-gould** [comment]
In my experience having the packaging in the same repo is really helpful. Usually you can grep for a dependency and change it everywhere at once and stuff like that. Not telling you how to run your project, but that has helped me in the past.

**Comment by ted-gould** [comment]
Made the listing in the store "unlisted" so you have to select it explicitly. But if anyone is seeing this PR and wants to try it out: https://snapcraft.io/adguard-home

**Comment by popey** [comment]
I'd not heard of AdGuard Home before. Thanks for doing this @ted-gould ! I have installed the snap on a raspberry pi at home and it's working perfectly! 🍾

@ameshkov - I work at Canonical (the company behind Ubuntu and Snapcraft). I am biassed of course, but I think it would be great to have an officially blessed build of AdGuard Home in the Snap Store. With your branding behind the snap, it would be more attractive to users if there's a verified developer associated with a network security snap of this nature.

Looking at the snapcraft configuration Ted proposed, it's very simple to maintain, our free multi-architecture automated build-and-publish service means little intervention required by you to publish new releases. Plus you get access to metrics in the store for how many weekly active devices there are with the software installed, and in what geographic regions.

I'd love to promote this snap using our social channels, and also a blog post, which has a pretty significant reach, if that would be attractive to you. 

Further, with the _very soon_ upcoming release of Ubuntu 20.04 LTS we have an initiative to build, distribute and promote Ubuntu Core appliance images. These showcase high quality professional applications such as yours, bundled on an Ubuntu Core image, easily downloaded and flashed to an SD card. Users can grab the image and be up and running with your product in minutes with little fuss. This initiative isn't intended to replace / supplant your existing distribution systems. It's merely an additional option and showcases the power of Ubuntu Core. 

Time is tight on that final one, but with the snap already existing and working really well, I think we could turn it around very fast. It'd be great to have a polished application like AdGuard in the list of appliances. 

If you have any questions I'm happy to answer them, or get on a call / hangout at your convenience.

**Comment by ameshkov** [comment]
@popey Hi Alan, that's awesome and we'd be interested of course!

> If you have any questions I'm happy to answer them, or get on a call / hangout at your convenience.

Thank you! I do have some questions, if you don't mind, I'll email you so that we could arrange a call.

**Comment by ameshkov** [comment]
@ted-gould I've tried building a snap using your configuration file, but for some reason it fails with a node error:
```
snapcraft-adguard-home ../parts/adguard-home/src# npm --prefix client ci
npm WARN prepare removing existing node_modules/ before installation
npm WARN lifecycle The node binary used for scripts is /snap/bin/node but npm is using /snap/node/2635/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> fsevents@1.2.8 install /root/parts/adguard-home/src/client/node_modules/fsevents
> node install

internal/modules/cjs/loader.js:955
  throw err;
  ^

Error: Cannot find module '/var/lib/snapd/void/install'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:15)
    at Function.Module._load (internal/modules/cjs/loader.js:835:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

Have you experienced anything like that?

**Comment by ted-gould** [comment]
Hmm, no I haven't. I built mine in a clean LXC container (I don't like having dev dependencies installed in my host OS). Which is probably the difference, it sounds like you have two versions of node installed. I'm using the snap for node in the build so that I know it stays updated, specifically latest stable on the 13 series.

If you have a LP account an easy way to build (and for ARM which I don't have a local machine to build) is with `snapcraft remote-build` -- that will upload the source to Launchpad and build it there in a clean environment.

**Comment by ameshkov** [comment]
@ted-gould 

Hm, weird, I can't build it locally, but it seems okay on build.snapcraft.io.

One more question: there are `restart:` and `status:` apps in your snap file, do they work on your side? They are supposed to work only in the case when AGH installs itself as a service, and it does not seem to be happening with the snap.

**Comment by ted-gould** [comment]
No, sorry, I took those out locally but forgot to commit the change. Inside the snap it doesn't have access to systemd. You can control the status of the service with snapctl though. Or externally through `snap stop` and `snap start`. Also, `snap logs` is really useful. Those are basically all of the systemd commands with the snap syntax added to them for you.

**Comment by ameshkov** [comment]
@ted-gould I've added config for a snap build and made it [work](https://github.com/AdguardTeam/AdGuardHome/blob/master/build_snap.sh) with our CI:
https://github.com/AdguardTeam/AdGuardHome/blob/master/packaging/snap/snapcraft.yaml

Here's the first result:
https://snapcraft.io/adguardhometest

If it looks okay to you and if you don't mind transferring the `adguard-home` name to our account, I'd be happy to set up automatic publishing of that snap.

**Comment by ted-gould** [comment]
I have tried to add you, I needed an email address so I guessed it was your username here AT adguard.com. If that's not correct, please send me the correct one. Otherwise we should be good!

**Comment by ameshkov** [comment]
@ted-gould it's `am@adguard.com`

**Comment by ameshkov** [comment]
@ted-gould got it, thank you! 

I wonder can it be transferred so that the publisher name changed so that we could get the verified developer badge there?

@popey could you please take a look?

**Comment by popey** [comment]
I've mailed the store team to request the transfer. It should be done today!

**Comment by ameshkov** [comment]
@ted-gould one more question: what was the point of putting AdGuardHome.yaml to SNAP_COMMON? I am thinking about changing it and placing it to SNAP_DATA.

**Comment by ameshkov** [comment]
@ted-gould the official snap is live so I guess we can close this pull request now.

Thank you so much for showing Snap Store to us!

**Comment by ameshkov** [comment]
Uh, and there's one more thing that I forgot to mention.

Since `AdGuardHome.yaml` is now located in `$SNAP_DATA`, this will cause settings to reset on update. We'd better do this now than later.

**Comment by ted-gould** [comment]
Cool, sorry for not replying quickly. I think the difference is largely what your preferences are. I tend to use `COMMON` for user modifyable things and `DATA` for internal stuff. A config file can go either way, especially in AdGuard where there is a nice UI for modifying it.

Thanks so much for taking this over and building AdGuard for homes!

**Pull request closed without merging**
