### PR TITLE
add Disney Plus streaming

### PR DESCRIPTION
**Pull request by andre68723**
missing: Icon

### CODE REVIEW

**Comment by Archive5** [comment]
@ameshkov I dont like such services add to blocked services and not interest to see about copying and doing the same poor thing that nextdns does. It's good to have limitation eg: only add world most popular services that social friendly, privacy hostiles, adult friendly(that still unable to consider for parental service) etc.

Several days ago added a comment related that https://github.com/AdguardTeam/AdGuardHome/issues/1203#issuecomment-615553752

**Comment by Archive5** [comment]
@andre68723 see https://github.com/AdguardTeam/AdGuardHome/issues/1692

**Comment by szolin** [comment]
Is there any icon that we can add here?

**Comment by uNitrous** [comment]
@subdavis @me two votes to stop add

**Comment by andre68723** [comment]
1692 is even better from parental perspective

**Pull request closed without merging**
