### PR TITLE
Use directory with upstream_dns_file

### PR DESCRIPTION
**Pull request by hellodword**
How do you think about this?

```
$ tree rules
rules
├── 01-default.txt
└── 02-use-doh.txt
└── 03-use-system.txt
└── 04-ads.txt
```

### CODE REVIEW

**Comment by ainar-g** [comment]
Hello again.  Feature requests should generally be discussed in Issues first.

@ameshkov, do we want this feature?

**Comment by ainar-g** [comment]
@ameshkov?

**Comment by ameshkov** [comment]
@hellodword could you please explain the need for this? IMO, it complicates things a little, but I don't see any direct benefit.

**Comment by hellodword** [comment]
> @hellodword could you please explain the need for this? IMO, it complicates things a little, but I don't see any direct benefit.

Sorry this is not a well-thought-out idea when I think it again now. I think it should be closed.

**Pull request closed without merging**
