### PR TITLE
Remove unwanted contents

### PR DESCRIPTION
**Pull request by Archive5**
@ameshkov consider update `line 304` sentence, even removed unwanted comma but it still has two `and` words nearly then seems ugly and i will update all translations however some are already had ignored unwanted punctuation marks

### CODE REVIEW

**Comment by szolin** [comment]
Hello!
Can you send your patch to Crowdin community?
https://adguard.com/en/blog/looking-for-moderators.html

**Comment by Archive5** [comment]
> Hello!
> Can you send your patch to Crowdin community?
> https://adguard.com/en/blog/looking-for-moderators.html

@szolin check source strings suggestions (@iStore) i'm not english language proofreader.

**Comment by ameshkov** [comment]
@Archive5 the point is that it'd be better to send the suggestion to Crowdin as we anyway import strings from there

**Comment by Archive5** [comment]
Already suggested but anyone needs to approve source strings in crowdin (this PR for that) and i'll update other languages soon.

**Comment by aalpatkina** [comment]
@Archive5 I replied to your suggestions in comments on Crowdin. Please check them. Let's further discuss suggestions to phrases on Crowdin. And do not forget to ping @adguard in comments.

**Pull request closed without merging**
