### PR TITLE
Update DNS servers

### PR DESCRIPTION
**Pull request by Aikatsui**
Update to adguard non-filtering DNS (close #1524)

### CODE REVIEW

**Comment by ameshkov** [comment]
We'll need to change much more than that in order to change this - check all the places where Quad servers are used in the code. Also, we'll need to change strings and translations.

**Comment by KizunaH** [comment]
> We'll need to change much more than that in order to change this - check all the places where Quad servers are used in the code. 

It seems no other places except https://github.com/AdguardTeam/AdGuardHome/blob/master/scripts/querylog/test/querylog.json

>Also, we'll need to change strings and translations.

Since recent versions, UI doesn't contain any details about default servers.

**Comment by ameshkov** [comment]
> Since recent versions, UI doesn't contain any details about default servers.

Quad9 is used in examples, I guess it makes sense to replace it there as well.

**Comment by KizunaH** [comment]
> Quad9 is used in examples, I guess it makes sense to replace it there as well.

I updated it seperately #2156

**Comment by KizunaH** [comment]
@ameshkov it take time to review commits history. maybe @szolin or @ArtemBaskal has removed it but why removed "If you keep this field empty. AdGuardHome will use [provider] as upstream" line.
I see it's possible to leave bootstrap field empty and use DOH address in upstream or upstream field empty and use boostrap address so i guess it's necessary to explain what happen when user keep particular field empty

"If you keep upstream or bootstrap field empty, AdGuardHome will use [provider] if necessary" you can suggest a beautiful sentence

**Pull request closed without merging**
