### PR TITLE
Add douyincdn.com to TikTok blocked rules

### PR DESCRIPTION
**Pull request by Hill-98**
douyincdn.com is cdn domain for china tiktok

### CODE REVIEW

**Review by reinasalondra — APPROVED** [review]

**Review by ameshkov — APPROVED** [review]

**Comment by ameshkov** [comment]
@ainar-g should we switch to https://github.com/AdguardTeam/HostlistsRegistry/blob/main/assets/services.json and update it instead?

**Comment by ainar-g** [comment]
Apologies for the extremely long wait.  We'll make sure to merge this into the next patch release.  Switching to the service index will take a long time.

**Comment by Hill-98** [comment]
@ainar-g No sorry, I just saw #4795 made the same change and we don't need this PR anymore.

**Comment by ainar-g** [comment]
Oh, indeed.  Once again, apologies for the very slow response.

**Pull request closed without merging**
