### PR TITLE
Update blocked services

### PR DESCRIPTION
**Pull request by KizunaH**
This covers user opened PR for blocked services recently

### CODE REVIEW

**Comment by DandelionSprout** [comment]
Personally I'm not sure if applying `.TLD` to `||vk.`, `||6pm.` or `||novi.` is a good idea, due to how short they are and the possibility they're used for non-corp purposes in smaller countries.

I also think we need an expert on `Cloudflare` and Amazon` to look through this PR.

Other than that it looks pretty good to me.

**Comment by szolin** [comment]
Looks like a pretty big change that can potentially break something.
Maybe it's better to apply just 1 smaller change at a time during several next releases? @ameshkov

**Comment by ameshkov** [comment]
@szolin well, that's why we have "edge" update channel :)

**Comment by KizunaH** [comment]
@DandelionSprout Sorry, i didnt noticed mail notifications.

>Personally I'm not sure if applying .TLD to ||vk., ||6pm. or ||novi. is a good idea, due to how short they are and the possibility they're used for non-corp purposes in smaller countries.

Updated. then let's wait for other hand (till someone say about certain ccTLD or gTLD not blocked)

>I also think we need an expert on Cloudflare and Amazon to look through this PR.

I checked properly then no problem with it except you want to add more domains because this list doesn't contain all amazon domains for example.

>@ameshkov @szolin well, that's why we have "edge" update channel :)

Does that already works without #1733 ? ;)

**Comment by ameshkov** [comment]
@KizunaH 

> Does that already works without #1733 ? ;)

Nope, not implemented yet

**Comment by szolin** [comment]
9b9902f0048e1bca5d0c55ff715fb226f6fbc6ac
@KizunaH Please note that we reverted the patch as it depends on #1733

**Pull request closed without merging**
