### PR TITLE
Update the comparison with the Pi-Hole

### PR DESCRIPTION
**Pull request by jvoisin**
- AGH is written in Go, which is memory-safe, instead of using dnsmasq which
  has a terrible security record.
- AGH is able to run without root privileges, while the Pi-Hole isn't.

### CODE REVIEW

**Comment by ainar-g** [comment]
Merged in 0801c89.

**Comment by ameshkov** [comment]
I don't fully agree about the "memory-safe language" point. This alone does not guarantee anything and can't be considered an advantage.

**Comment by jvoisin** [comment]
It does guarantee the absence of memory-safety related issues, which is no small feat.

**Comment by ameshkov** [comment]
To be honest, I still find this point kinda misleading. The fact that a program is written in a memory-safe language does not guarantee that it's more secure than the other one, written in C/C++. Yes, some of the issues are solved automatically, but there're always other ways. Only time will show which one is safer :).

**Pull request closed without merging**
