### PR TITLE
Update DNS examples

### PR DESCRIPTION
**Pull request by KizunaH**
Update rest of examples to AG DNS not only quic protocol address

### CODE REVIEW

**Comment by KizunaH** [comment]
@ArtemBaskal why that commit seems deleted from master?

**Comment by ameshkov** [comment]
@KizunaH our bad, we should've merged it to internal repo first, otherwise it gets overwritten.

Could you please create a new one. Just one note - use `dns-unfiltered.adguard.com` in examples.

**Comment by KizunaH** [comment]
> Could you please create a new one. Just one note - use `dns-unfiltered.adguard.com` in examples.

@ameshkov it already added to #2157 and this's about examples. it can be adguard or other provider according to user's choice. Everyone use `dns.provider.com` style subdomain then `dns-unfiltered` name may feel complicated to non-technical user

Should i use `dns-unfiltered.adguard.com` for examples?

**Comment by ameshkov** [comment]
Tbh, I think you should. People will still copy/paste it from the example, and they'd better copy/paste the unfiltered version

**Comment by KizunaH** [comment]
> @KizunaH our bad, we should've merged it to internal repo first, otherwise it gets overwritten.

See https://github.com/AdguardTeam/AdGuardHome/pull/2188 Can't PR again 🤗

**Pull request merged**
