### PR TITLE
Update servicelist.go

### PR DESCRIPTION
**Pull request by rootmelo92118**
resource : https://github.com/v2fly/domain-list-community/blob/master/data/ebay

### CODE REVIEW

**Comment by EugeneOne1** [comment]
@rootmelo92118, hello.  Unfortunatelly, we can't accept these changes here, since the file itself is generated by the script, so it shouldn't be modified manually, see the following line:

https://github.com/AdguardTeam/AdGuardHome/blob/cfab157146c8f4ac4b19fb21620958906b36c4e1/internal/filtering/servicelist.go#L1

We regularly update these lists on each release using the [HostlistsRegistry](https://github.com/AdguardTeam/HostlistsRegistry/) repo as the source (particularly, the [services.json](https://github.com/AdguardTeam/HostlistsRegistry/blob/main/assets/services.json) file), so you actually may open a PR there.  I'll close this and similar ones.

**Comment by rootmelo92118** [comment]
Ok thanks.

**Comment by rootmelo92118** [comment]
And please help me to close the pull request

**Comment by EugeneOne1** [comment]
@rootmelo92118, did it already.

**Pull request closed without merging**
