### PR TITLE
Rolling log files #1573

### PR DESCRIPTION
**Pull request by DannyHinshaw**
This PR brings in the feature for rolling logs. Implemented by bringing in [lumberjack](https://github.com/natefinch/lumberjack) as was suggested [on the issue](https://github.com/AdguardTeam/AdGuardHome/issues/1573#issuecomment-625310216).

Additionally, new config file properties have been added to further configure the lumberjack output:

```
// logSettings
type logSettings struct {
	LogCompress   bool   `yaml:"log_compress"`    // Compress determines if the rotated log files should be compressed using gzip (default: false)
	LogLocalTime  bool   `yaml:"log_localtime"`   // If the time used for formatting the timestamps in is the computer's local time (default: false [UTC])
	LogMaxBackups int    `yaml:"log_max_backups"` // Maximum number of old log files to retain (MaxAge may still cause them to get deleted)
	LogMaxSize    int    `yaml:"log_max_size"`    // Maximum size in megabytes of the log file before it gets rotated (default 100 MB)
	LogMaxAge     int    `yaml:"log_max_age"`     // MaxAge is the maximum number of days to retain old log files
	LogFile       string `yaml:"log_file"`        // Path to the log file. If empty, write to stdout. If "syslog", writes to syslog
	Verbose       bool   `yaml:"verbose"`         // If true, verbose logging is enabled
}
```

### CODE REVIEW

**Comment by DannyHinshaw** [comment]
```
+golangci-lint run
home/home.go:9: File is not `goimports`-ed (goimports)
	"gopkg.in/natefinch/lumberjack.v2"
```

CI fail looks to be linter related. What is the proper way to fix this error?

**Comment by ameshkov** [comment]
> CI fail looks to be linter related. What is the proper way to fix this error?

You may need to write something like 
```
import (
    lumberjack "gopkg.in/natefinch/lumberjack.v2"
)
```

Also, I suggest installing `golangci-lint` locally and running it to see if there are any other linter issues like this.

**Comment by ameshkov** [comment]
@DannyHinshaw thank you!

**Comment by DannyHinshaw** [comment]
@ameshkov you're welcome! Is it going to be merged? I'm unfamiliar with how the team processes PR's.

**Comment by szolin** [comment]
It's already merged!

**Comment by Freebase394** [comment]
Guys! Thanks so much for this "Feature"
Its so nice to have it on this project AdGuardHome and it's so usefull.

I love it! 
image


I apologize for the inconvenience out of the blue, or for no reason! 
I just wanted to say it, because those who contribute sometimes do not always receive the necessary recognition! 
Thank you

**Pull request closed without merging**
