### PR TITLE
Add qq to blocked services

### PR DESCRIPTION
**Pull request by ifurther**
Add the qq to blocked services

### CODE REVIEW

**Comment by Archive5** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/1692

**Comment by ameshkov** [comment]
Bad bot. @ArtemBaskal please take care

**Comment by ArtemBaskal** [comment]
Merged https://github.com/AdguardTeam/AdGuardHome/commit/32b24ce0930cbdb9b759f77f2c0773f3e61cb7b3

**Comment by gtaphash** [comment]
@ameshkov  when block `qq.com` domain (qq app, mailbox, office suites) then it brake access to `wechat.com`, localized web browser/ updates `browser.qq.com`, desktop/security solutions updates `guanjia.qq.com` and other third-party sites depend on qq.
This blocked service cannot take control over all products or services compared to existing services also leave some applications vulnerable 🤔

**Comment by ameshkov** [comment]
@gtaphash what do you suggest?

**Comment by gtaphash** [comment]
> @gtaphash what do you suggest?

This may need to limit for `im.qq.com` (IM app) and `mail.qq.com` (mailbox) which means by qq but `qq.com` has local news site. otherwise add ⓘ button to explain about possible issues when block it in a network. Generally IM app site, root domain etc available in local language and said browser, desktop/security softwares so far use or purchase by local people although might has attraction for qq app or this service can remove according to one of my opinion and let people to add these type of services via custom blocked services https://github.com/AdguardTeam/AdGuardHome/issues/1692

**Comment by ameshkov** [comment]
Well, we could do that I guess, but I think that would be kinda misleading. Offering to block QQ, but not even blocking its homepage is weird.

Let's maybe consider unblocking specifically the domain that breaks `wechat.com`? 

> and other third-party sites depend on qq.

Depend in which way? Any examples?

**Comment by gtaphash** [comment]
>Let's maybe consider unblocking specifically the domain that breaks wechat.com?
>Depend in which way? Any examples?

Depend on `qq.com` CNAME and that looks like a kill-switch (PR seems come from taiwan, i don't know) 😄

>Let's maybe consider unblocking specifically the domain that breaks wechat.com?

Site: `weixin.qq.com` `wx.qq.com`(static) `dldir1.qq.com`(downloads) `akm.qq.com`(downloads)
other usage: `weixin.qq.com` `imtt.qq.com` maybe has other. sign-up stuck from my country (not ISP issue)

Google Play
QQ - 10 million installs (since 2011 sep release)
QQ mail - 1 million installs (since 2013 jan release)
Wechat - 100 million installs (since 2011 jan release)

It's much lower than telegram - 500 million installs

Or isn't it good to add 'WeChat' instead? 
Site available in english by default and ago USA wanted to block it

**Comment by ameshkov** [comment]
> Depend on qq.com CNAME and that looks like a kill-switch (PR seems come from taiwan, i don't know) 😄

Oh, this makes sense.

> Or isn't it good to add 'WeChat' instead?

I guess we should add an option for WeChat as well.
Maybe Weibo as well? Baidu?

**Comment by ameshkov** [comment]
> Google Play

Well, since Google Play does not work on the mainland, I don't think the numbers from there are reasonable.

Also, the point of "Blocked services" is to allow users quickly disabling this or that service on the per-client basis.
For instance, if you'd like to prevent kids from chatting/playing, you could do that for their devices.

**Comment by gtaphash** [comment]
>Well, since Google Play does not work on the mainland, I don't think the numbers from there are reasonable.

It's about how much particular app popular worldwide and there're so many chinese people use skype(also companies), gmail(even it blocked), hotmail and i clearly know that there also 2-3k members contain chinese groups in telegram (mostly those are not counted). eg: baidu seems just a search engine in chinese language https://www.baidu.com/

>Or isn't it good to add 'WeChat' instead?
>>I guess we should add an option for WeChat as well.

so more, kik, imo, hike/jio/indian messenger, viber, icq and others
(actually need to have standard for blocked services part) eg: add only dominated services or lack privacy friendly services or add option to select services under particular categories (regardless popular or not)

there're world dominated services out there. people interest to use them, usually tend to despite or lack interest for own country things so i'm really not interested ***local friendly(qq, yandex messenger)** or ***privacy friendly(wire,telegram, signal)** services get added. 

As i said above, this feature extension #1692 may help for custom services and it's upto you to decide what to do and treat the product. ago i saw qq domain brake wechat and other sites, that was another reason for add a comment

**Comment by KizunaH** [comment]
>(actually need to have standard for blocked services).... or select services under particular categories
Screenshot from 2020-10-24 20-40-53

**Comment by KizunaH** [comment]
Above argument reasonable; regional focused apps often has low installation rate even they're accessible around the world.

Screenshot from 2020-10-25 19-5


Past i addressed an issue about add microsoft, amazon, reddit, google, cloudflare, yandex, origin and ignored 1* 4* 6* companies because of their products, adguardhome especially designed for home users (not for enterprises that aware about IT). Amazon partially blocked due their hosting platform  and yandex ignored due their web browser (also same for QQ browser and their offline usable tools)

Current blocked services page has 'block all' and 'unblock all' buttons on the top. It means for home users, Oh! let's block these hipop services with just one click

>Also, the point of "Blocked services" is to allow users quickly disabling this or that service on the per-client basis.
For instance, if you'd like to prevent kids from chatting/playing, you could do that for their devices.

Then need to implement feature similar below for advanced blocking(for only effect to each category services and cover worldwide solutions) while let to remaining existing blocked services component with custom option #1692, current behavior doesn't make sense. just kids find alternative in next minute

>(actually need to have standard for blocked services).... or select services under particular categories

Screenshot from 2020-10-24 20-40-53

**Comment by ameshkov** [comment]
> (actually need to have standard for blocked services) eg: add only dominated services or lack privacy friendly services or add option to select services under particular categories (regardless popular or not)

The reason for blocking a service may not just be whether it's privacy-friendly or not.

Anyways, I filed a new issue so that we don't forget about that: https://github.com/AdguardTeam/AdGuardHome/issues/2224

@KizunaH
> Then need to implement feature similar below for advanced blocking

I kinda agree and disagree at the same time:)

IMO, it's hard for people to realize what actual services are behind these categories. It's just easier to understand what exactly is being blocked when you see the names and the logos.

**Comment by KizunaH** [comment]
>Also, the point of "Blocked services" is to allow users quickly disabling this or that service on the per-client basis.
>For instance, if you'd like to prevent kids from chatting/playing, you could do that for their devices.

>>I kinda agree and disagree at the same time:)
>>
>>IMO, it's hard for people to realize what actual services are behind these categories. It's just easier to understand what exactly is being blocked when you see the names and the logos.

Just a comment. let me know if it good to implement and need to open feature request.

I can realize the point of view but this isn't a perfect solution for parental control or access prevention to certain category services at all (belongs to individual/kids/co-workers) unless let users to disable access for dominant internet companies.
The propose new solution will address that properly and adguardhome has lot of users already so they'll definitely help if missing something.
- block youtube but there're dtube, vimeo, rutube...
- block tiktok but there're chingari, dubsmash, triller...

The benefit: Each category will provide most effective coverage. eg: block IM apps then DNS server owner can unblock only the required app for server users to communicate (eg: skype) 

About social media:
May be okey to add weibo since far known as chinese social media but i don't recommend to add other regional services. Already has 10M+ adguardhome docker downloads. i dont want see this become one of another source that bring foreigners to regional sites and expand various disappointing troubles than today.
(Since this 'blocked services' component come from nextdns and only has facebook in it; later they started to offer special toggle option called 'social media' to cover rest of all services). it's similar above proposed solution

**Comment by ameshkov** [comment]
What I mean is that ideally, we should allow both: blocking by categories AND/OR blocking a single popular service.

I haven't given this enough thought though.

**Pull request closed without merging**
