### PR TITLE
Add Dockerfiles

### PR DESCRIPTION
**Pull request by ewrogers**
Added Dockerfiles for Linux (386, amd64, and arm)

Tested working on RPi3+ as well.

```
docker run -d \
    -p 53:53 \
    -p 53:53/udp \
    -p 80:3000 \
    -v adguard_data:/data/adguard \
    --restart always \
    --name adguard-home \
    ewrogers/adguard-home-arm:latest
```
Able to visit http://adguard-home in my browser and DNS queries are handled. Settings also persist across container restarts.

### CODE REVIEW

**Comment by hmage** [comment]
Thank you for your contribution 🎉

**Comment by HenryQW** [comment]
`-v ~/adguard/AdGuardHome.yaml:/data/adguard/AdGuardHome.yaml`

Seems this will break the container.

**Comment by ewrogers** [comment]
Does it do similar if you use absolute paths instead of the `~/adguard` prefix?

I have noticed similar oddities with other containers in the past, trying to mount single files into a volume. Will take a look.

**Comment by HenryQW** [comment]
No luck, my workaround:
```
docker exec AdGuardHome rm /data/adguard/AdGuardHome.yaml
docker cp ~/adguard/AdGuardHome.yaml AdGuardHome:/data/adguard/AdGuardHome.yaml
docker restart AdGuardHome
```

**Comment by frenck** [comment]
So... the binary is stored in the data volume...?
How are you planning on handle upgrades?

**Comment by ewrogers** [comment]
Correct, this is a problem. I only did it that way because pre-hotfix the binary wouldn't look in a data directory.

A proper solution would be to only use the volume as a data directory (non-binary). Haven't had time to fix/test that it works.

**Comment by frenck** [comment]
Thx, I'll work around it for the Hass.io add-on.

**Pull request merged**
