### PR TITLE
CI revamped and more

### PR DESCRIPTION
**Pull request by crazy-max**
First of all thank you for offering AdGuardHome, it's really what I was looking for as a lightweight alternative to Pi-hole.

This PR offers a pretty big redesign of the CI to have a minimum of devops maintenance but also something more versatile. This way, we will be limited to a few dev and production commands.

I would have liked to do several PRs but this was not possible because of the changes that were made. Here is a short summary:

* CI revamped and other enhancements
* GoReleaser for multi-arch binaries
* Switch to GitHub Actions (more versatile) with 2 workflows
* Docker multi-manifest image with buildx
* Go sum fix
* Use tools.go paradigm for external dependencies (packr)
* Use go generate for packr

In order to be able to test my modifications I would first need to activate the GitHub Actions on the repository if it is not already done and also add the secrets as I mention in the changelog below. I'm really hype to work with you on this if your roadmap allows it ;)

Here is what it looks like on my fork: https://github.com/crazy-max/AdGuardHome/actions/runs/112195639

## Changelog

* Add `.dockerignore`
* Global ignore for packr files
* ~~Fix eslint run script~~ (fixed through rebase)
* Add goreleaser config
  * Multi arch binaries
  * Snapcraft
* Only one Dockerfile with multi-platform support through Buildx
* Go sum cleaned
* Use tools.go paradigm for external dependencies (packr)
* Use `go generate` for packr
* Add Open Container Specification labels to Dockerfile
* Switch to GitHub Actions (more versatile) with 3 jobs for build workflow
  * Test
    * 3 platforms (linux,windows,macos) to enhance coverage
    * Cache go modules and node_modules
    * golangci-lint ported
    * eslint
    * Go tests ported
    * Coverage uploaded to Codecov
  * App
    * Cache go modules and node_modules
    * npm ci and build-prod
    * Snapcraft Login (if tag)
    * GoReleaser release or snapshot if not a tag
    * Create GitHub release to publish assets as draft for review (if tag)
  * Docker multi-arch manifest
    * On release: create x.x.x and latest tags
    * On snapshot: crate edge tag
    * Install docker buildx
    * Docker build
    * Docker login (if tag)
    * Docker push (if tag)
    * Image manifest check (if tag)
    * Clear Docker credentials on post (if tag)
* Add simple workflow to fix go.sum if not "tied"
* GitHub Actions secrets have to be added to the repo: `CODECOV_TOKEN`, `SNAPCRAFT_LOGIN`, `DOCKER_USERNAME`, `DOCKER_PASSWORD`

And thanks to buildx (Buildkit), we have a single multi-arch image. Will look like this on DockerHub:

image

## Local dev commands

* `npm --prefix client ci`
* `npm --prefix client run build-prod`
* `CHANNEL=none goreleaser release --rm-dist --snapshot`
* `docker build -t adguardhome -f ./Dockerfile .`

## TODO

* [X] Add Slack notification
* [ ] Make a review of snapcraft build
* [ ] Update documentation

### CODE REVIEW

**Comment by ameshkov** [comment]
Wow, thank you, this is some serious work!

We may need to change our usual routine to start using goreleaser, but it seems that it may be worth it.

Note that we keep some private stuff in our internal CI, and I am not yet sure how to make them all work together. For instance, publishing to static.adguard.com and Snapcraft, signing assets, we'd better do this from the internal CI.

One question about goreleaser -- does it support splitting build and publish?

**Comment by crazy-max** [comment]
Hi @ameshkov,

> One question about goreleaser -- does it support splitting build and publish?

Yes this is what I've done [here](https://github.com/crazy-max/AdGuardHome/blob/3fcfbf8d4406a8cc48fb300ea29b07fbd7edd607/.github/workflows/build.yml#L146-L166). I build with GoReleaser Action and push [only on tag](https://github.com/crazy-max/AdGuardHome/blob/3fcfbf8d4406a8cc48fb300ea29b07fbd7edd607/.github/workflows/build.yml#L157) with GitHub Release action.

> Note that we keep some private stuff in our internal CI, and I am not yet sure how to make them all work together. For instance, publishing to static.adguard.com and Snapcraft, signing assets, we'd better do this from the internal CI.

Oh ok I was not aware of this limitation looking at your code. I have removed unnecessary files to show you a "preview". Kind of ^^

About publishing to your CDN we can use an action to upload through FTP/SFTP? And also, GoReleaser supports [Snapcraft](https://goreleaser.com/customization/snapcraft/) as you can see in the [.goreleaser.yml](https://github.com/crazy-max/AdGuardHome/blob/3fcfbf8d4406a8cc48fb300ea29b07fbd7edd607/.goreleaser.yml#L48-L71) I made. And [signing](https://goreleaser.com/customization/sign/) too!

> We may need to change our usual routine to start using goreleaser, but it seems that it may be worth it.

I think @caarlos0, the owner of GoRelease, can tell you more about it ;)

**Comment by ameshkov** [comment]
> About publishing to your CDN we can use an action to upload through FTP/SFTP?

It's just we'd like to keep some things private without any option to have this kind of access from a public network. Maybe we can pull it from GH, I'll think about it.

**Comment by crazy-max** [comment]
@ameshkov 

> It's just we'd like to keep some things private without any option to have this kind of access from a public network.

Oh ok I misunderstood this part.

> Maybe we can pull it from GH, I'll think about it.

Yes sure, you can cron/poll this through GitHub API: https://api.github.com/repos/AdguardTeam/AdGuardHome/releases/latest

**Comment by caarlos0** [comment]
> It's just we'd like to keep some things private without any option to have this kind of access from a public network. Maybe we can pull it from GH, I'll think about it.

you could use a custom publisher for that - https://goreleaser.com/customization/publishers/ - or upload to a s3/gcs/azure bucket...

**Comment by Archive5** [comment]
hhttps://github.com/AdguardTeam/AdGuardHome/issues/1265

**Comment by ameshkov** [comment]
@caarlos0 thank you!

@Archive5 
> #1265

Tbh I am still not sure what we should do about that and what exactly is wrong:(

**Comment by crazy-max** [comment]
@ameshkov 

> Tbh I am still not sure what we should do about that and what exactly is wrong:(

It's quite easy, specially for a Go app which can handle multi-arch natively. As you can see in my [Dockerfile](https://github.com/crazy-max/AdGuardHome/blob/master/Dockerfile), there are specially crafted [args](https://github.com/crazy-max/AdGuardHome/blob/master/Dockerfile#L9-L10) used by [buildx](https://github.com/docker/buildx). Then I [translate those args with `GOOS` and `GOARCH`](https://github.com/crazy-max/AdGuardHome/blob/9310b0671b463e9b614357c749f0691cab6db174/Dockerfile#L11-L21) and we are good to go in the first stage to build the app.
The last stage only takes care to copy the asset in a fresh alpine.

**Comment by crazy-max** [comment]
@ameshkov [Slack notification](https://github.com/crazy-max/AdGuardHome/blob/812cb6043b8b72a4e715eccd3ba991647ee9e974/.github/workflows/build.yml#L233-L249) is [effective](https://github.com/crazy-max/AdGuardHome/runs/700010385?check_suite_focus=true#step:3:1) on my fork. You just need to set the `SLACK_WEBHOOK_URL` secret.

image

**Comment by ameshkov** [comment]
@crazy-max would it be possible to limit this to some specific repo (as it was done in the travis config)? Otherwise, we'll get notified of every fork build.

**Comment by crazy-max** [comment]
@ameshkov You will not be notified if a fork use this action. Secrets are not shared.

**Comment by ameshkov** [comment]
Ah, yep, makes sense

**Comment by crazy-max** [comment]
@ameshkov More info: https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#using-encrypted-secrets-in-a-workflow

image

**Comment by crazy-max** [comment]
@ameshkov And btw, on Travis I use [this trick](https://github.com/portapps/portapps/blob/master/.travis/configs/notifs.yml#L5) to limit notification propagation.

**Comment by crazy-max** [comment]
@ameshkov Ready to be reviewed. Let me know if you have any questions!

**Comment by ameshkov** [comment]
@crazy-max sorry for the delay, I remember and I am going to review it, but I am completely out of time this week:(

**Comment by crazy-max** [comment]
@ameshkov No rush, keep me in touch :)

**Comment by ameshkov** [comment]
@crazy-max sorry for the delay, I've finally started merging with your PR and changing our internal CI.

I may need to split it into three parts, though. This won't require more coding from you as I've already started doing that locally, but I'd really appreciate it if you could answer some of my questions below.

1. Goreleaser seems really-really nice and it fits just okay. Your version can be used right away with some minor changes to the configuration.
2. Github actions -- I don't see much difference compared to Travis. Could you please explain what advantages it provides?
3. Docker. This one bothers me most of all.  I don't really like the idea of building AdGuardHome binaries extra time when the multi-arch image is being prepared. Maybe I am wrong, but I just like short and simple docker files :). So the question is: is it possible to avoid building AGH again and reuse the dist prepared by goreleaser?

**Comment by crazy-max** [comment]
Hey @ameshkov!

> I may need to split it into three parts, though.

Yes we can split this PR, sure.

> Goreleaser seems really-really nice and it fits just okay. Your version can be used right away with some minor changes to the configuration.

Ok let me know if you need further assistance with that.

> Github actions -- I don't see much difference compared to Travis. Could you please explain what advantages it provides?

I was also on Travis and for me GitHub Actions require minimum of devops maintenance but it's also more versatile and organized inside your repo (multi workflows). There is also [many actions](https://github.com/marketplace?type=actions) you can use like the [GoReleaser Action](https://github.com/goreleaser/goreleaser-action) to avoid statically defined procedures like Travis. And finally, build time is reduced compared to Travis.

> Docker. This one bothers me most of all. I don't really like the idea of building AdGuardHome binaries extra time when the multi-arch image is being prepared. Maybe I am wrong, but I just like short and simple docker files :). So the question is: is it possible to avoid building AGH again and reuse the dist prepared by goreleaser?

I tend to build the binaries in the Docker image in order to respect the interoperability of it (kernel behavior). Since the new Docker image I propose here is now multi-platform, building is done in parallel for each of them thanks to buildkit so its build time is reduced.

And a developer is not a devops so their environment can vary. That's why a devops (or everyone else) will only need Docker if he intends to build the image without worrying about all the ancillary tools (Go, GoReleaser, etc..) and his based OS. This allows almost maximum reproducibility.

**Comment by ameshkov** [comment]
Makes sense, thank you!

What's the purpose of "tonistiigi/xx:golang" image there? I am a little bit worried about using unverified images there.

**Comment by crazy-max** [comment]
@ameshkov 

> Regarding Dockerfile, what's the purpose of "tonistiigi/xx:golang" image there? I am a little bit worried about using unverified images there.

`tonistiigi/xx:golang` is just here to [transposed buildkit platform to go compiler's target platform](https://github.com/tonistiigi/xx/blob/2fa69fdb0ad72e0d8dee61c906ddf8a7956cca69/golang/wrapper.sh).

And @tonistiigi is a software engineer at Docker and a maintainer of Moby/Docker engine so I think it's fine ;)
Maybe this image can be made official in the Docker organization. What do you think @tonistiigi?

**Comment by ameshkov** [comment]
@crazy-max 

Here's one more question about Docker build. The multi-platform build with buildx fails on my Mac:
` => ERROR [linux/amd64 builder 10/12] RUN npm --prefix client ci && npm --prefix client run build-prod                                                              172.6s`

buildx build without `--platform` argument is successful. What could be the issue?

**Comment by crazy-max** [comment]
@ameshkov 

> it seems that the problem is the parallel build. The build is successful when I set just a single platform in the --platform argument (regardless of which platform I set there).

That's maybe a cache issue. What's command are you using?

**Comment by ameshkov** [comment]
> That's maybe a cache issue. What's command are you using?

This repo:
https://github.com/ameshkov/AdGuardHome

The command is `make docker`

```
DOCKER_CLI_EXPERIMENTAL=enabled \
	docker buildx build \
	--platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/386,linux/ppc64le,linux/s390x \
	--build-arg VERSION=0.102.0-SNAPSHOT-762cabe \
	--build-arg CHANNEL=release \
	--build-arg VCS_REF=762cabe \
	--build-arg BUILD_DATE= \
	--tag adguard/adguardhome:0.102.0-SNAPSHOT-762cabe \
	--output "type=image,push=false" \
	-t "adguard/adguardhome" -f ./Dockerfile .
```

**Comment by ameshkov** [comment]
Hm, the docker build also fails on Github Actions: https://github.com/ameshkov/AdGuardHome/runs/841727822

The error is different, though:
```
#77 116.8 main.go:2: running "packr": signal: illegal instruction (core dumped)
#77 ERROR: executor failed running [/bin/sh -c go generate ./...]: buildkit-runc did not terminate successfully
```

**Comment by crazy-max** [comment]
@ameshkov After investigating, that's because `linux/s390x` is not supported by packr.

**Comment by ameshkov** [comment]
@crazy-max thank you, I'll test it now.

**Comment by ameshkov** [comment]
@crazy-max 

Yep, works okay on Github Actions, thank you!

The issue with building multi-arch image on Mac is [still there](https://github.com/AdguardTeam/AdGuardHome/pull/1718#issuecomment-654187956), though.

I suppose it's specific to Docker Desktop, but it's a little bit annoying anyways. I might have to use a VM to test the Dockerfile locally.

**Comment by crazy-max** [comment]
@ameshkov 

> Yep, works okay on Github Actions, thank you!

Great!

> The issue with building multi-arch image on Mac is [still there](https://github.com/AdguardTeam/AdGuardHome/pull/1718#issuecomment-654187956), though.

Can you open an issue on https://github.com/docker/buildx about that please?

**Comment by ameshkov** [comment]
@crazy-max yep, good idea: https://github.com/docker/buildx/issues/319

**Comment by ameshkov** [comment]
@crazy-max quick update - it seems that my issue with running `npm` was caused by the fact that it was unnecessarily run multiple times while we could run it just once: https://github.com/docker/buildx/issues/319

Fixed it in my fork, looks okay: https://github.com/ameshkov/AdGuardHome/commit/1b919c5932790879a41889398df348541791b291

**Comment by crazy-max** [comment]
@ameshkov LGTM. I copied `go.mod` and `go.sum` originally to `go mod download` only if changes occurred but in our case the use of arguments prevented that indeed.

**Comment by ameshkov** [comment]
@crazy-max I've been able to make everything work in a fork so it seems we'll be able to use all three things - GH actions, docker buildx and goreleaser.

One more thing before that -- could you please rebase and squash your commits so that I could merge it and keep the repo history clean?

**Comment by crazy-max** [comment]
@ameshkov 

> I've been able to make everything work in a fork so it seems we'll be able to use all three things - GH actions, docker buildx and goreleaser.

:tada:

> One more thing before that -- could you please rebase and squash your commits so that I could merge it and keep the repo history clean?

You should be able to squash and merge here no?

image

**Comment by ameshkov** [comment]
@crazy-max 

I suspect that in this case this will be seen as my own commit in the history and I think it’d be better to retain your authorship as you contributed a lot of work

**Comment by crazy-max** [comment]
@ameshkov I solved the conflict and updated the latest upstream changes

**Comment by crazy-max** [comment]
@ameshkov If you squash and merge my work will be retained as one commit, don't worry ;)

**Comment by crazy-max** [comment]
@ameshkov As an example:

* https://github.com/crazy-max/diun/pull/100
* https://github.com/crazy-max/diun/commit/db2bce3bb386c2123b5244bd351c19a56257c3fa

**Comment by ameshkov** [comment]
@crazy-max what I mean is that the squashed commit looks like mine and not yours, see example: https://github.com/AdguardTeam/AdGuardHome/commit/49646cf706dac1c2998d91f4a6f109b5026dabdd

If you don't mind, I can do that of course.

**Comment by crazy-max** [comment]
@ameshkov Hum I think that's because your "squash and merge" from your Git client and not GitHub:

image

**Comment by ameshkov** [comment]
Got it, thank you!

Merged to a branch: https://github.com/AdguardTeam/AdGuardHome/commit/ff23d7b6d73b2a138774ca0919692246f62c0177

I'll apply my changes on top of it later and merge to the master branch, I'll keep you updated in this PR.

**Comment by ameshkov** [comment]
@crazy-max finally, it has been merged to the master branch, thank you!

1. We now use your Dockerfile and publish multi-arch images to Docker Hub (check the "edge" and "beta" tags there).
2. We're using Github Actions to check all branches and pull requests, but building releases & publishing them is done by our internal CI.
3. Added makefile and updated README to reflect the build process changes

**Comment by crazy-max** [comment]
@ameshkov 

> finally, it has been merged to the master branch, thank you!

Argh my commits have been stripped :confused: I thought you were gonna merge that PR and the other PR #1873 was just a trial run. Not a big deal but I'm not tagged as a contributor :sweat_smile:

But if everything is functional on your side, that's good!

**Comment by ameshkov** [comment]
Uh, sorry about that. We'll mention your contribution in the release notes, though :)

**Pull request closed without merging**
