### PR TITLE
Blocked services API: List available services

### PR DESCRIPTION
**Pull request by RoboMagus**
Related to FR #4520 

This PR adds `GET` `/blocked_services/services` that will return a full list of the service names that can be blocked using the blocked_services API.

It seemed quite easy to implement, though I must declare that I am __NOT__ proficient in Go...

### CODE REVIEW

**Comment by ainar-g** [comment]
Hello and thank you for that contribution!  We've actually planned to postpone that until a proper API refactoring that we planned to do later in the v0.108 cycle, but since you've already provided an implementation, we'll try to review your contribution next week.  Be aware, though, that when the refactoring comes, it is likely that this API will be rewritten.

**Comment by RoboMagus** [comment]
Thanks for taking a look into this. It's good to hear that these api changes are already on the roadmap. In that case it might be best to first iron out what the api should look like.

Is there an estimated time frame for when v0.108 is to be released? Cause then I'll postpone work on my integration that interacts with the api until it arrives.

**Comment by frenck** [comment]
This feature is very much wished for, for the Home Assistant project as well. It would allow us to create switches in Home Assistant to automate on. Right now, we can't, as we can't get a list of services.

**Comment by ainar-g** [comment]
@RoboMagus, @frenck, we have decided to merge this into v0.107.12.  Thank you for the contribution!

**Comment by NebzHB** [comment]
Dears,
Is it possible to have the full name in that service list too ? example : 'ok' is displayed 'OK.ru' in the web interface ('disneyplus' : 'Disney+', ...)

**Pull request merged**
