### PR TITLE
add cpu temperature

### PR DESCRIPTION
**Pull request by Ahmame**
add cpu temperature and percentage of memory usage

### CODE REVIEW

**Comment by ainar-g** [comment]
Hello.  It seems like there are no changes here?  And the release branch must not be merged into `master`.  If you have changes in a branch, could you please make them in a single commit on top of the current `master`?

Also, it's generally considered good practice to notify the maintainers in an issue before contributing big changes.

Thanks.

**Comment by Dynasty-Dev** [comment]
anything?

**Comment by Dynasty-Dev** [comment]
Hello

**Comment by Bluscream** [comment]
Memory usags would indeed be useful

**Comment by markhecht99** [comment]
Any news on this request?

**Comment by Freebase394** [comment]
Any Update on this ?
This technology within AGH itself could be very valuable!

**Comment by 6twenty** [comment]
Looks like the base branches on this PR have gotten messed up so this doesn't appear to be in a mergeable state. It's been well over a year, this PR should really be closed.

**Comment by Bluscream** [comment]
Or it should just be fixed and merged so the feature is finally in

**Comment by 6twenty** [comment]
There's nothing to fix; OP doesn't even have a fork of the repo any more, so the branch with the changes is missing. Both the target and base branches on this PR are both internal branches within this repo, and neither of them have anything to do with adding cpu temp and memory info.

**Comment by Bluscream** [comment]
well, if you get served food on a silver plate, eventually it will spoil if you wait long enough 🪦

**Comment by 6twenty** [comment]
https://github.com/AdguardTeam/AdGuardHome/pull/4294#issuecomment-1040218646

> It seems like there are no changes here?

There was never any food, it's always been a dud PR right from the start.

**Comment by ainar-g** [comment]
@6twenty is correct.  There weren't any discernable changes, and OP hasn't responded since, so closing.

**Pull request closed without merging**
